local home = os.getenv("HOME")

hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("swaync")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd(home .. "/.config/waybar/launch.sh")
    hl.exec_cmd("sleep 1 && kitty --class dropdown-terminal")
    hl.exec_cmd(home .. "/.config/hypr/scripts/autostart.sh")
end)
